### ISSUE TITLE
nav: unnecessary gaps in sidebar

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#724] opened 2019-10-22 20:24 UTC
I think there is unnecessary space between 'Shared Development Server' and 'User Guide'.
![Screenshot from 2019-10-22 00-05-06](https://user-images.githubusercontent.com/35191225/67328867-b595a380-f537-11e9-9696-5f50de12fb18.png)

UPDATE: Note that a PR for this could also solve this related issue: #856

**Comment by shcheklein** [comment] 2019-10-22 20:34
@algomaster99 I can's reproduce this. What browser do you use? Is it production?

**Comment by jorgeorpinel** [comment] 2019-10-22 20:41
I also don't see this. Try ford reloading the site on your browser Aman. Shall we close as `invalid`?

**Comment by algomaster99** [comment] 2019-10-22 20:44
@shcheklein @jorgeorpinel I sometimes see this and sometimes not. I can't figure out what is happening.

**Comment by shcheklein** [comment] 2019-10-22 20:47
@algomaster99 could you check the console? could you check the inspector in this place?

**Comment by algomaster99** [comment] 2019-10-22 20:51
@shcheklein 
![Screenshot from 2019-10-23 02-20-14](https://user-images.githubusercontent.com/35191225/67331668-aca6d100-f53b-11e9-9a51-39c775d2f5b3.png)

The harcoded `height: 119px` might be a problem. I will have too see.

**Comment by jorgeorpinel** [comment] 2019-10-22 22:04
I get 94px correctly. But I was able to reproduce from https://www.webpagetest.org/result/191022_SR_d9e1db4a5e961674a3f0fd9d512cd22a/ so it's definitely not just Aman's browser.

**Comment by shcheklein** [comment] 2019-10-22 22:09
@algomaster99 @algomaster99 does it happen with other sections?

**Comment by algomaster99** [comment] 2019-10-23 06:07
@shcheklein No, I don't think so.

**Comment by shcheklein** [comment] 2019-10-23 18:58
Got the same problem with this configuration:

<img width="409" alt="Screen Shot 2019-10-23 at 11 56 40 AM" src="https://user-images.githubusercontent.com/3659196/67425131-4f873b80-f58c-11e9-939f-12985e9c5900.png">

Probably related to the way item height is calculated when it's close to the very edge and close to taking two lines

**Comment by iAdramelk** [comment] 2019-12-10 15:58
I think I found out why this bug happens:

1. We use custom font Brandon on our site, but before font file is loaded other font is shown (system default sans-serif font).
2. And sans-serif is wider then the Brandon. Because of that some menu items are wrapped to the second line.
3. So if the script that calculates block height for animations is fired before font was loaded it calculates incorrect height which results in the bug.

There is a few possible solutions for this problem:

1. Add `white-space: nowrap` to links, it will prevent the bug, but we will not be able to have multiline links anymore.
2. Make menu column wider to prevent line number from changes.
3. Start listening to the font loading event before measuring block height (but sections will stay closed for some time before font loaded).
4. Remove animations from opening and closing submenus.
5. Replace css-animations there with some library that will do it in js. (Will make our bundle larger)

I'd prefer first solution, but like to discuss it with everyone before implementing.

**Comment by shcheklein** [comment] 2019-12-10 18:01
Thanks, @iAdramelk - good investigation!

Let me clarify a few things re the proposed solutions:

> Add `white-space: nowrap` to links, it will prevent the bug, but we will not be able to have multiline links anymore.

No multiline items anymore, right? How would we render those that do not fit? Can we simplify the code besides `white-space: nowrap` (height calculate, etc)

> Make menu column wider to prevent line number from changes.

Not sure how would it solve it. Could you elaborate?

> 3-4-5

All of them sound hacky and/or suboptimal to me.

Agreed on the first one if understand it right ... but we should properly cut the text with `...` and show the full name when you hover, for example, if it's too wide to fit into the column and simplify all the logic around multiline support.

**Comment by jorgeorpinel** [comment] 2019-12-11 19:54
> > 1. Add `white-space: nowrap` to links...
>
> No multiline items anymore, right? How would we render those that do not fit?

So this has already been implemented guys? I see long items are truncated (without "..." or hover text) into a single line now e.g.:

![image](https://user-images.githubusercontent.com/1477535/70655047-62250500-1c0c-11ea-9c1b-694bc46abd0b.png)

![image](https://user-images.githubusercontent.com/1477535/70655061-694c1300-1c0c-11ea-87f1-39ff6b62d91a.png)

> 3. Start listening to the font loading event before measuring block height...

I also like this one. I don't see it being hacky. Could display a "loading navigation" thingy meanwhile in case it lags noticeably but do we really expect this lag to be noticeable? Maybe just the very first time a person loads it after deploying updates to prod.

**Comment by iAdramelk** [comment] 2019-12-12 02:08
No, I didn't have time to implement in so far. Text still should still wrap lines right now. If it didn't it is possible that it happens because of the same bug with the wrong height.

**Comment by jorgeorpinel** [comment] 2019-12-12 20:50
Ah yes, they do wrap. I was editing the last item in an expanded section, and the next line is hidden after it wraps. This is how the previous item looks when elongated:

![image](https://user-images.githubusercontent.com/1477535/70747888-c368d900-1cdd-11ea-897c-439b8826e628.png)

(The next item, **Community Tutorials**, becomes invisible as it goes over the height of the **Tutorials** container div.)

**Comment by jorgeorpinel** [comment] 2019-12-27 08:52
> From https://github.com/iterative/dvc.org/pull/882#issuecomment-569098104

Please double check the error `Warning: NaNis an invalid value for theheight css style property.` from line 29 in

https://github.com/iterative/dvc.org/blob/9ee6eac5baa0bf952ff4a6a9d216041c56e63299/src/Documentation/SidebarMenu/SidebarMenu.js#L26-L29

is not repeated in the new implementation.

**Closed** 2020-02-13 19:21 UTC
Labels: bug, doc-engine, priority-p1
