### ISSUE TITLE
install: add snap option

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#918] opened 2020-01-13 22:44 UTC
@casperdcl as we discussed, could you please add this method to the docs as `snap` is official now?

**Comment by jorgeorpinel** [comment] 2020-01-18 20:25
Seems like a duplicate of #904 @schuhschuh ?

**Comment by shcheklein** [comment] 2020-01-18 20:45
@jorgeorpinel no, this is one is simpler - just add the option. No need to think about ordering.

**Comment by casperdcl** [comment] 2020-01-18 22:55
Ah right, will do

**Closed** 2020-01-22 17:44 UTC
Labels: doc-content, enhancement

**Comment by casperdcl** [comment] 2020-01-22 19:13
btw did we want to use any images/badges anywhere?

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/dvc) [![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/dvc) [![dvc](https://snapcraft.io//dvc/badge.svg)](https://snapcraft.io/dvc)

**Comment by shcheklein** [comment] 2020-01-22 19:15
it can be a good idea to try to embed them into docs

**Comment by casperdcl** [comment] 2020-01-22 19:26
well in that case what of the other badges from the readme?

[![Release](https://img.shields.io/badge/release-ok-brightgreen)](https://travis-ci.com/iterative/dvc)
[![Travis dev branch](https://img.shields.io/travis/com/iterative/dvc/master?label=dev)](https://travis-ci.com/iterative/dvc)
[![Code Climate](https://codeclimate.com/github/iterative/dvc/badges/gpa.svg)](https://codeclimate.com/github/iterative/dvc)
[![Codecov](https://codecov.io/gh/iterative/dvc/branch/master/graph/badge.svg)](https://codecov.io/gh/iterative/dvc)
[![Donate](https://img.shields.io/badge/patreon-donate-green.svg)](https://www.patreon.com/DVCorg/overview)
[![Conda-forge](https://anaconda.org/conda-forge/dvc/badges/version.svg)](https://anaconda.org/conda-forge/dvc)
[![Snapcraft](https://img.shields.io/badge/snap-install-82BEA0.svg?logo=snapcraft)](https://snapcraft.io/dvc)

Also, what's up with the sneaky https://img.shields.io/badge/release-ok-brightgreen ? A hardcoded "status is ok" badge sort of defeats the purpose
