### ISSUE TITLE
menu not scrolled up appropriately after contraction

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#309] opened 2019-05-10 07:06 UTC
This happens when we switch from a menu with many items to other one with much fewer of them. Look at how scrollbar disappears when I scroll up:
![dvc-org-menu-bug](https://user-images.githubusercontent.com/284103/57508754-9d84eb80-732c-11e9-804a-850717b1e450.gif)

**Comment by iAdramelk** [comment] 2019-08-27 19:08
@shcheklein I investigated this bug some more and looks like that the source of the problem is combination of PerfectScrollbar and using animations for opening/closing directories:

1. After scroll container content changes we need to run PerfectScrollbar.update() function to update container height because PS didn't detect those changes by itself.
2. But right now update is called before the end of animations, so it gets wrong height.

There is few different ways to fix this problem:

1. Add timeout to `update()` call. It will fix the problem, but only after 400ms. All this time scroll container height will be incorrect.
2. Remove animations from opening/closing categories. Looks worse, but works without bugs.
3. Remove PerfectScrollobar – no more bugs, but ugly scrollbars on Windows.
4. Remove scroll from menu – in some cases left column will be longer then content, but no problems with scroll, animations and visuals.

**Comment by iAdramelk** [comment] 2019-08-28 11:47
@shcheklein Any browser. I will add timeout to this branch and create separate branch for version without scroll.

**Closed** 2019-09-06 21:43 UTC
Labels: bug, docs, engine, priority-p1
