### ISSUE TITLE
nav: left sidebar isn't visible without js

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#856] opened 2019-12-11 23:22 UTC
~~Disclaimer: I'm not sure the title is completely accurate.~~ See https://github.com/iterative/dvc.org/pull/834#pullrequestreview-330780455 for context Summary:

> J: without js the nav bar doesn't expand
> I: The good question is if we need to generate a sitemap or something for the case when we don't have a link to some page inside and search engines won't be able to find it?
> J: maybe it's easy to pre-render nav?

So, possible solutions:

1. Pre-render all nav elements
2. Introduce a (automatic) site map.

**Comment by jorgeorpinel** [comment] 2019-12-11 23:23
Thoughts @iAdramelk?

**Comment by iAdramelk** [comment] 2019-12-12 01:55
Not exactly. NextLink is wrapping the regular links and passing the href for them. So in the generated HTML, there are always exists regular links with the correct href attribute. On the client navigation through this links is prevented by Event.preventDefault(), and Next's logic is used instead, but crawlers and users can just use regular links and hrefs as usual.

**Comment by iAdramelk** [comment] 2019-12-12 02:12
But the submenus that are not visible without JS is a problem. We probably should fix it together with #724. And it means that we should remove the need for set height to display submenu, so either remove animations or implement them in some other way.

**Comment by jorgeorpinel** [comment] 2019-12-12 23:41
> So in the generated HTML, there are always exists regular links with the correct href attribute.

So you're saying the SSR HTML does have the full nav regardless of JS? (Meaning the site can be easily crawled.)

> But the submenus that are not visible without JS is a problem...

Agree but would not combine that with #724. Would just change the title and description of this issue.

**Comment by shcheklein** [comment] 2019-12-12 23:48
Just to be precise - the title is not exactly correct, btw - most engines crawl the website easily since they support JS. So, it's more about optimization, including SEO of course. And SSR itself is more about proper behavior with things like 404 and optimization again.

**Comment by shcheklein** [comment] 2019-12-12 23:50
also, NextLink is "crawlable", the problem is with nav bar only as far as I understand (as it was before without SSR).

**Comment by jorgeorpinel** [comment] 2019-12-29 09:08
> submenus that are not visible without JS is a problem.

@iAdramelk are they just not visible but the HTML is there? Because in that case this may not be a problem after all.

**Comment by iAdramelk** [comment] 2019-12-29 12:27
@jorgeorpinel yep, just not visible. Because we can't calculate submenus height correctly on the server, we just assign them height 0. But it still would be a good thing to have working menus even without the js.

**Comment by jorgeorpinel** [comment] 2019-12-29 23:44
OK so they ARE rendered, but with height 0. I then agree with Alexey's idea:

> We probably should fix it together with #724. And it means that we should remove the need for set height to display submenu, so either remove animations or implement them in some other way.

Do you agree @shcheklein ? If so I'll move this requirement over to that existing issue.

**Comment by shcheklein** [comment] 2019-12-30 02:04
@jorgeorpinel I would keep them separate. They are too different. It just happened that a PR for that one can close this one as well.

**Closed** 2020-02-13 19:21 UTC
Labels: doc-engine, enhancement
