### ISSUE TITLE
get-started: dvc run: command not found on Windows

### ISSUE THREAD

**Issue by SpicySyntax** [iterative/dvc.org#486] opened 2019-07-12 18:44 UTC
I have been working through the getting started portion of this project but have run into a snap at [this part](https://dvc.org/doc/get-started/connect-code-and-data)

I have setup the data and src tree as described:
```
.
├── data
│   ├── data.xml
│   └── data.xml.dvc
├── requirements.txt
└── src
    ├── evaluate.py
    ├── featurization.py
    ├── prepare.py
    └── train.py
```

but when I run:
```bash
dvc run -f prepare.dvc \
          -d src/prepare.py -d data/data.xml \
          -o data/prepared \
          python src/prepare.py data/data.xml
```
I get:
```
Running command:
        python ./src/prepare.py ./data/data.xml
The system cannot find the path specified.
ERROR: failed to run command - stage 'prepare.dvc' cmd python ./src/prepare.py ./data/data.xml failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

But I am able to run the following successfully
```bash
python src/prepare.py data/data.xml
```

I am not sure what exactly is wrong here. Thanks for any help

**Comment by shcheklein** [comment] 2019-07-12 19:18
@SpicySyntax hi! let's try to reproduce and help you out here. Can you give a little bit more details - what OS do you use? Windows/Linux/Mac?

**Comment by SpicySyntax** [comment] 2019-07-12 19:38
Sure @shcheklein!
windows 10.0.16299
Python 3.6.8 :: Anaconda, Inc. (Miniconda)
pip 19.0.3
I am using GitBash to run the commands

**Comment by efiop** [comment] 2019-07-13 17:51
Hi @SpicySyntax !

Could you please run
```
dvc run -f prepare.dvc \
          -d src/prepare.py -d data/data.xml \
          -o data/prepared -v \
          python src/prepare.py data/data.xml
```
(notice, I've added `-v`)
and show us the log?

**Comment by efiop** [comment] 2019-07-13 17:57
@SpicySyntax Also, I've noticed that the command in your logs differs a little bit, so I wonder if there was a typo somewhere.

**Comment by efiop** [comment] 2019-07-13 21:00
@SpicySyntax Also, could you please show `dvc version` output? It contains a bit more info than the version itself.

**Comment by shcheklein** [comment] 2019-07-14 05:15
More context: https://discordapp.com/channels/485586884165107732/565699007037571084/599335950665121813

**Comment by shcheklein** [comment] 2019-07-21 20:45
@SpicySyntax was not able to reproduce it. I tried to use GiBash + miniconda. Both `dvc run` and `dvc repro -s prepare.dvc` work fine for me. Can you give us more context here please? Windows setup is tricky - a lot of moving parts and we need to see how specifically bash, conda, windows PATH are set for you.

**Comment by SpicySyntax** [comment] 2019-07-22 14:12
@efiop 
#### DVC Version output
```bash
dvc version
DVC version: 0.51.2
Python version: 3.6.8
Platform: Windows-10-10.0.16299-SP0
Binary: False
Cache: reflink - False, hardlink - True, symlink - False
Filesystem type (cache directory): ('NTFS', 'D:\\')
Filesystem type (workspace): ('NTFS', 'D:\\')
```

#### Verbose output from one line command
```bash
dvc run -f prepare.dvc -d src/prepare.py -d data/data.xml -o data/prepared -v python src/prepare.py data/data.xml
DEBUG: Trying to spawn '['c:\\users\\nick.purcell\\appdata\\local\\continuum\\miniconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: Spawned '['c:\\users\\nick.purcell\\appdata\\local\\continuum\\miniconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
DEBUG: Skipping copying for 'D:\POC\DVC\example-get-started\data\prepared\test.tsv', since it is not a symlink or a hardlink.
DEBUG: Skipping copying for 'D:\POC\DVC\example-get-started\data\prepared\train.tsv', since it is not a symlink or a hardlink.
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(2,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
DEBUG: Removing output 'data\prepared' of 'prepare.dvc'.
DEBUG: Removing 'data\prepared'
Running command:
        python src/prepare.py data/data.xml
DEBUG: Computed stage 'prepare.dvc' md5: 'ed8f290985048ecfe88fcc6d7c959b1b'
The system cannot find the path specified.
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(2,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
ERROR: failed to run command - stage 'prepare.dvc' cmd python src/prepare.py data/data.xml failed
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\command\run.py", line 53, in run
    outs_persist_no_cache=self.args.outs_persist_no_cache,
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\repo\scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\repo\run.py", line 69, in run
    stage.run(no_commit=no_commit)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\stage.py", line 863, in run
    self._run()
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\stage.py", line 820, in _run
    raise StageCmdFailedError(self)
dvc.stage.StageCmdFailedError: stage 'prepare.dvc' cmd python src/prepare.py data/data.xml failed
------------------------------------------------------------

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!

```
@shcheklein 
#### User Path Environment variable
![image](https://user-images.githubusercontent.com/19228996/61639182-99e0df80-ac60-11e9-811d-f53d21a53247.png)

#### System Path Environment variable
pt1:
![image](https://user-images.githubusercontent.com/19228996/61639239-b5e48100-ac60-11e9-9ef7-35678f7bde84.png)

pt2:
![image](https://user-images.githubusercontent.com/19228996/61639284-d0b6f580-ac60-11e9-84b3-79f8d20af94d.png)


Thanks

**Comment by efiop** [comment] 2019-07-22 23:11
@SpicySyntax Hm, weird. Let's try something smaller, so it is easier to pinpoint to see what went wrong. Try running these commands:
```
python --version
dvc run python --version
```
and
```
where python
dvc run where python
```

**Comment by SpicySyntax** [comment] 2019-07-23 13:34
Note I updated the following (still obtained the same error as above):
Python 3.7.3
pip 19.2
conda 4.7.10

@efiop Here is the requested output

```bash
Nick.Purcell@Naou22002 MINGW64 /D/POC/DVC/example-get-started (master)
$ python --version
Python 3.7.3
(.env)
Nick.Purcell@Naou22002 MINGW64 /D/POC/DVC/example-get-started (master)
$ dvc run python --version
Running command:
        python --version
The system cannot find the path specified.
Python 3.7.3
ERROR: failed to run command - stage 'Dvcfile' cmd python --version failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
(.env)
Nick.Purcell@Naou22002 MINGW64 /D/POC/DVC/example-get-started (master)
$ where python
D:\POC\DVC\example-get-started\.env\Scripts\python.exe
C:\Users\Nick.Purcell\AppData\Local\Continuum\miniconda3\python.exe
(.env)
Nick.Purcell@Naou22002 MINGW64 /D/POC/DVC/example-get-started (master)
$ dvc run where python
Running command:
        where python
The system cannot find the path specified.
D:\POC\DVC\example-get-started\.env\Scripts\python.exe
C:\Users\Nick.Purcell\AppData\Local\Continuum\miniconda3\python.exe
ERROR: failed to run command - stage 'Dvcfile' cmd where python failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
(.env)

```

**Comment by shcheklein** [comment] 2019-07-23 19:13
@SpicySyntax that's interesting. It looks like it's running the command, the issue is happening somewhere inside? I'm not sure yet and I don't know how to reproduce it. 

Btw, it looks like conda is not activated. Can you try to run `conda activate`?

Also, can you try to remove data.dvc and run `dvc add data.xml`? To see if it creates the file at all. To make sure that's all related to running the command.

**Comment by SpicySyntax** [comment] 2019-07-24 19:14
@shcheklein I obtained the following results using the anaconda prompt.

```bash
conda activate
```
This got rid of the multiple python paths seen above. 

I deleted data.xml.dvc. And recreated it with
```bash
# This now passes
dvc add data.xml
```
And this did not seem to fix anything.

Running the commands from I obtained @efiop seen [here](https://github.com/iterative/dvc.org/issues/486#issuecomment-513988984):
```
(base) D:\POC\DVC\example-get-started>python --version
Python 3.6.8 :: Anaconda, Inc.

(base) D:\POC\DVC\example-get-started>dvc run python --version
Running command:
        python --version
The system cannot find the path specified.
Python 3.6.8 :: Anaconda, Inc.
ERROR: failed to run command - stage 'Dvcfile' cmd python --version failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!

(base) D:\POC\DVC\example-get-started>dvc init
ERROR: failed to initiate dvc - '.dvc' exists. Use '-f' to force.

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!

(base) D:\POC\DVC\example-get-started>where python
C:\Users\Nick.Purcell\AppData\Local\Continuum\miniconda3\python.exe

(base) D:\POC\DVC\example-get-started>dvc run where python
Running command:
        where python
The system cannot find the path specified.
C:\Users\Nick.Purcell\AppData\Local\Continuum\miniconda3\python.exe
ERROR: failed to run command - stage 'Dvcfile' cmd where python failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

The origin command executed as follows:
```
(base) D:\POC\DVC\example-get-started>dvc run -f prepare.dvc -d src/prepare.py -d data/data.xml -o data/prepared python src/prepare.py data/data.xml
Running command:
        python src/prepare.py data/data.xml
The system cannot find the path specified.
ERROR: failed to run command - stage 'prepare.dvc' cmd python src/prepare.py data/data.xml failed

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!

(base) D:\POC\DVC\example-get-started>dvc run -f prepare.dvc -d src/prepare.py -d data/data.xml -o data/prepared -v python src/prepare.py data/data.xml
DEBUG: Trying to spawn '['c:\\users\\nick.purcell\\appdata\\local\\continuum\\miniconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: Spawned '['c:\\users\\nick.purcell\\appdata\\local\\continuum\\miniconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
DEBUG: Skipping copying for 'D:\POC\DVC\example-get-started\data\prepared\test.tsv', since it is not a symlink or a hardlink.
DEBUG: Skipping copying for 'D:\POC\DVC\example-get-started\data\prepared\train.tsv', since it is not a symlink or a hardlink.
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(3,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
DEBUG: Removing output 'data\prepared' of 'prepare.dvc'.
DEBUG: Removing 'data\prepared'
Running command:
        python src/prepare.py data/data.xml
DEBUG: Computed stage 'prepare.dvc' md5: 'ed8f290985048ecfe88fcc6d7c959b1b'
The system cannot find the path specified.
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(3,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
ERROR: failed to run command - stage 'prepare.dvc' cmd python src/prepare.py data/data.xml failed
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\command\run.py", line 53, in run
    outs_persist_no_cache=self.args.outs_persist_no_cache,
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\repo\scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\repo\run.py", line 69, in run
    stage.run(no_commit=no_commit)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\stage.py", line 863, in run
    self._run()
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\lib\site-packages\dvc\stage.py", line 820, in _run
    raise StageCmdFailedError(self)
dvc.stage.StageCmdFailedError: stage 'prepare.dvc' cmd python src/prepare.py data/data.xml failed
------------------------------------------------------------

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by shcheklein** [comment] 2019-07-25 06:15
@SpicySyntax could you check if this link helps in your case by any chance https://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified ?

**Comment by ryokugyu** [comment] 2019-07-25 11:29
@SpicySyntax will you try to execute the command by specifying the absolute path to the files.

I also use Windows machine but I am unable to reproduce the issue. It works fine on my system.

**Comment by elepherai** [comment] 2019-07-29 09:51
@ryokugyu same problem with absolute path.

**Comment by shcheklein** [comment] 2019-07-29 16:20
@elepherai could you share your output, especially with `-v` flag. Could you please try the link above that I shared - https://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified ?

**Comment by elepherai** [comment] 2019-07-30 07:20
@shcheklein Thanks! The method in your link works.

**Comment by shcheklein** [comment] 2019-07-30 16:13
@elepherai glad that it helped. Closing it for now since it looks like it's not a DVC problem.

**Closed by shcheklein** 2019-07-30 16:13 UTC
Labels: bug, docs, get-started

**Comment by SpicySyntax** [comment] 2019-07-31 21:33
@shcheklein The [Link](https://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified) you sent me fixed the issue I was facing. Thanks!

**Comment by erarunn** [comment] 2023-07-24 12:06
(base) C:\WINDOWS\system32>dvc doctor -v
2023-07-24 17:34:07,809 DEBUG: v2.56.0 (exe), CPython 3.10.11 on Windows-10-10.0.19042-SP0
2023-07-24 17:34:07,809 DEBUG: command: doctor -v
Traceback (most recent call last):
  File "git\__init__.py", line 89, in <module>
  File "git\__init__.py", line 78, in refresh
  File "git\remote.py", line 359, in refresh
  File "git\cmd.py", line 781, in version_info
  File "git\cmd.py", line 740, in __getattr__
  File "gitdb\util.py", line 253, in __getattr__
  File "git\cmd.py", line 760, in _set_cache_
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc\cli\__init__.py", line 210, in main
  File "dvc\cli\command.py", line 40, in do_run
  File "dvc\commands\version.py", line 13, in run
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "dvc\info.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "dvc\scm.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scmrepo\git\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "git\__init__.py", line 91, in <module>
ImportError: Failed to initialize: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "git\__init__.py", line 89, in <module>
  File "git\__init__.py", line 78, in refresh
  File "git\remote.py", line 359, in refresh
  File "git\cmd.py", line 781, in version_info
  File "git\cmd.py", line 740, in __getattr__
  File "gitdb\util.py", line 253, in __getattr__
  File "git\cmd.py", line 760, in _set_cache_
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc\__main__.py", line 7, in <module>
  File "dvc\cli\__init__.py", line 236, in main
  File "dvc\cli\__init__.py", line 145, in _log_exceptions
  File "dvc\cli\__init__.py", line 41, in _log_unknown_exceptions
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "dvc\info.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "dvc\scm.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scmrepo\git\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "git\__init__.py", line 91, in <module>
ImportError: Failed to initialize: list index out of range
[3532] Failed to execute script '__main__' due to unhandled exception!

(base) C:\WINDOWS\system32>





Hi i am getting the error in windows, please can you help?

**Comment by dberenbaum** [comment] 2023-07-24 12:36
@erarunn Have you tried to install a different DVC version to see if it fixes the problem? If you still have trouble, could you create a new issue in https://github.com/iterative/dvc/issues? It will be more visible than posting here.

**Comment by erarunn** [comment] 2023-07-25 05:06
i have added two things in environment variable , and now its working ,
1. set GIT_PYTHON_REFRESH=quiet
2. set GIT_PYTHON_GIT_EXECUTABLE=C:\Program Files\Git\bin
