### ISSUE TITLE
Wrong item highlighted in the right menu

### ISSUE THREAD

**Issue by iKBAHT** [iterative/dvc.org#1306] opened 2020-05-18 14:05 UTC
Str:
1) go to https://dvc.org/doc/command-reference/diff
2) click to "Example" item in the right menu

Actual:
"Example: Checking workspace changes" item will be highlighted

Expected:
"Example" item will be highlighted

Some ideas:
https://github.com/iterative/dvc.org/blob/master/src/components/Documentation/RightPanel/index.tsx#L44
A peculiarity of the navigation algorithm

**Comment by jorgeorpinel** [comment] 2020-05-18 18:23
I think this is basically a duplicate of #753. @iKBAHT please add details in that one and close this one? thanks

**Closed** 2020-05-18 18:34 UTC
Labels: bug, doc-engine, duplicate
