### ISSUE TITLE
Reference VS Code (and Studio?) for DVC plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3718] opened 2022-07-01 15:14 UTC
### Report

Some places where it would be helpful to mention VS Code (and maybe Studio):

https://dvc.org/doc/command-reference/plots

This might seem odd in a CLI ref, but right now it states:

> DVC generates plots as static HTML webpages that can be open with a web browser. They can also be saved as SVG or PNG image files from the browser.

Since VS Code provides a better experience, why not mention it?

https://dvc.org/doc/start/experiments/visualization

@jorgeorpinel @shcheklein Thoughts?

**Comment by jorgeorpinel** [comment] 2022-07-05 23:10
Agree to both (VS Code and Studio).

Probably in https://dvc.org/doc/start/experiments/visualization first and foremost.

> might seem odd in a CLI ref

It's OK to add to the CLI ref too, since most of the plots info is there still (will get extracted [eventually](https://github.com/iterative/dvc.org/issues/2572))

**Comment by jorgeorpinel** [comment] 2022-07-05 23:11
Or maybe in the parent (https://dvc.org/doc/start/experiments) even.

**Comment by jorgeorpinel** [comment] 2022-07-06 00:00
Started #3735 for the VS Code links.

The pending question is: do we add Studio links in all (or most) places where VS Code is linked from? Or just the plots-related ones for now (i.e. in the same PR) ?

**Comment by jorgeorpinel** [comment] 2022-07-06 00:21
Wait this looks mostly like a dupe of https://github.com/iterative/dvc.org/issues/3717.

**Closed by jorgeorpinel** 2022-07-06 00:21 UTC
Labels: type: enhancement, A: content
