### ISSUE TITLE
docs: remove unnecessary index pages that serve as a table of contents

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#727] opened 2019-10-23 19:15 UTC
**Blocked by #738**

E.g. https://dvc.org/doc/user-guide/contributing

It'll be very painful to support them. We will need to keep titles up to date, list of them, snippets, etc, etc.

Let's not use pages like this at all or come with a way to generate them automatically.

cc @dashohoxha

**Comment by jorgeorpinel** [comment] 2019-10-24 00:14
The point of having them is that we can add some text about the purpose of the section, and summary of each page inside. All of those texts are custom, they don't come from inside any of the other pages. So auto-generating them won't be able to get these same results, so I think the decision is either keep them or remove them. If we don't want to have to maintain them, let's just delete all these index.md files.

**Comment by shcheklein** [comment] 2019-10-24 00:20
@jorgeorpinel yep, I don't mean pages that have some unique content or some introductory text. I specifically mean pages https://dvc.org/doc/user-guide/contributing that do not have any new content but repeat the structure. Moreover I really like that page, but I understand that it'll be a nightmare to keep those in sync w/o proper tooling.

**Comment by dashohoxha** [comment] 2019-10-24 02:00
> Let's not use pages like this at all

I have tried ` "source": false,` on `sidebar.json`, but it doesn't work (unless it is the top level, like `understanding-dvc`). Maybe it should be fixed on the engine.

> come with a way to generate them automatically

Again this seems like it needs to be fixed on the engine. I could be specified with a field like `"source": "auto",` or `"source": "index",`

**Comment by dashohoxha** [comment] 2019-10-24 02:12
> If we don't want to have to maintain them, let's just delete all these index.md files.

@jorgeorpinel As I said above, currently this is not possible, as it breaks the engine. Maybe this could be regarded as bug too, because I would expect it to work automatically without index pages.

> so I think the decision is either keep them or remove them

I agree with @shcheklein , sometimes they are useful, sometimes they are a burden. I think that autogenerating an index page should be the default, unless the `"source"` is given explicitly, or is specified as `false`.

**Comment by shcheklein** [comment] 2019-10-24 04:39
@dashohoxha 

> As I said above, currently this is not possible

It should be possible - check understanding DVC and/or changelog sections.

**Comment by jorgeorpinel** [comment] 2019-10-24 05:53
> yep... I specifically mean pages https://dvc.org/doc/user-guide/contributing

Ah, Ok. Never mind Ivan.

> I have tried ` "source": false,` on `sidebar.json`, but it doesn't work (unless it is the top level, like `understanding-dvc`)... it breaks the engine. Maybe this could be regarded as bug...

I'm able to reproduce this bug. I would say just delete the indexes and open a separate bug issue @dashohoxha. (We could wait for that fix before merging this PR.) All parent slugs with `"source": false` should behave like `understanding-dvc`, that opens **Collaboration Issues** by default. BTW it should also change the URL to `.../collaboration-issues` no? (part of the bug report)

> I think that autogenerating an index page should be the default...

Automatically generating a list of H2s in child documents when no `source` field is used for a parent `slug` is an engine feature that could also be worked on, but separate to the change I suggested above.

**Comment by shcheklein** [comment] 2019-10-24 20:40
@jorgeorpinel could you please create a ticket to fix the issue with indexes? Do you want to try to take it? :)

**Comment by jorgeorpinel** [comment] 2019-10-25 00:36
Opened #738. So this one is now just to delete all indexes as I suggested? Updating title

**Comment by shcheklein** [comment] 2019-10-25 02:25
Yep, I would clarify that not all indexes - only that do not provide any extra value and can be generated in the future.

**Comment by jorgeorpinel** [comment] 2019-10-26 04:41
I'm confused. What is the difference between this issue and #738? Seems to me like this one at least depends on that one. We could probably re-merge them?

**Comment by shcheklein** [comment] 2019-10-26 06:26
Yeo, this one depends on #738, but they are different anyway. I would keep them separate for simplicity.

**Comment by jorgeorpinel** [comment] 2020-01-07 02:39
OK I'm working on this one now. @shcheklein. One question, what about
- https://dvc.org/doc/command-reference/cache,
- https://dvc.org/doc/command-reference/metrics,
- https://dvc.org/doc/command-reference/pipeline, and
- https://dvc.org/doc/command-reference/remote
? They have useful, unique content but I'm not sure the cmd ref is the best place for those explanations. Should we take the opportunity to move them into a new **user-guide: "Basic Concepts" (#550)?

**Comment by jorgeorpinel** [comment] 2020-01-07 02:49
Hmmm. Actually the only other index left that definitely isn't useful in the cmd ref is for `tutorials` (besides the `user-guide/contributing` one). See draft PR #903 ^

I'm not sure about https://dvc.org/doc/use-cases or https://dvc.org/doc/user-guide. I'd like to remove them (so we don't have to maintain those bullet lists manually) but they do have some small unique paragraphs explaining the sections, and they forces users to chose the topic they're looking for... Thoughts?

**Closed** 2020-01-08 20:10 UTC
Labels: docs, enhancement
