### ISSUE TITLE
[spike] example repo topics & naming

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#3151] opened 2022-01-05 10:21 UTC
From https://github.com/iterative/dvc.org/pull/3087#discussion_r777304564, we should:

- name example repos consistently, and
- have a convention for adding [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to repos

Maybe:

repo name | repo [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) | description
--|--|--
`example-*` | `demo`, `example`, `docs` | used in official docs
`blog-*` | `demo`, `blog` | used in blog posts
`course-*` | `demo`, `course` | used in official courses
`test-*` | `demo`, `test` | debugging & CSE

Alternatives names & topics which are also inconsistently used include `learn`, `eg`, `intro`, `scenario`, `lesson`.

Repo [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) make it easy to find/filter repos and are probably more important than repo name. [iterative topic:example](https://github.com/iterative?q=topic%3Aexample&type=source) lists only one repo atm :cry:

There are ~150 repos in total and it's quickly getting impossible to keep track.

**Comment by casperdcl** [comment] 2022-01-05 10:27
> I began to believe having a dedicated Github organization like `iterative-examples` might be a better approach for the example repos. We can fork an example repository to a new name, modify it and use in a blog post/document. At least the fork lineage becomes trackable that way, and we can keep the tags, READMEs and whatnot.
> 
> Personally, I like the current approach better, but planning them centrally and building them with a script (like `example-repos-dev`) seems not scalable when teams have deadlines to meet.

-- @iesahin https://github.com/iterative/dvc.org/pull/3087#discussion_r777472797

> if we want to create a plethora of content with examples, having all example repos under Iterative is not sustainable. In my opinion, the examples for the official course and documentation (if needed) should be under Iterative. Everything else - examples for blog, talks, workshops, meetups, and so on are fine to be under personal accounts. These are meant to be temporary.

-- @MKhalusova https://github.com/iterative/dvc.org/pull/3087#discussion_r778090710

> > These are meant to be temporary.
> 
> not sure about this to be honest. We want to have them around at least for some time with some guarantees. Personal account doesn't guarantee anything. Also, it feels that there is an easy way to "solve" this with prefixes or a separate account like folks suggested.

-- @shcheklein https://github.com/iterative/dvc.org/pull/3087#discussion_r778223452

**Comment by jorgeorpinel** [comment] 2022-01-05 16:05
> name example repos consistently

I vote for prefixes but if people prefer a 2nd organization I don't see a problem with that either. Well, repos would still need prefixes under iterative-examples though... So not sure how it helps other than moving less important repos out of the main org. which seems like a separate question.

> have a convention for adding topics to repos

Lools like https://github.com/topics/ are meant to be specific technologies for anyone on Github to explore. "DVC" would be a topic. "demo", "example", "blog" have meanings internal to Iterative so should be labels or/and prefixes.

**Comment by iesahin** [comment] 2022-01-06 14:56
> > name example repos consistently
> 
> I vote for prefixes but if people prefer a 2nd organization I don't see a problem with that either. Well, repos would still need prefixes under iterative-examples though... So not sure how it helps other than moving less important repos out of the main org. which seems like a separate question.

Prefixes are good. I don't have any objections. Nevertheless, I don't think we can enforce this. We had a very simple rule to add `example` as a prefix to the repository name but we can't even let people to conform to this. To my mind, if everyone doesn't conform to a convention (and it's _expensive_ to enforce than to forgo), better to cancel it and find alternative ways to deal with the chaos. 

Having a different organization at least will say "we create example repositories here, not in `iterative/`" Creating repositories under `iterative` can be made an admin-level permission that way. 

I don't think we can maintain a prefix policy for repositories in the long run. Even if we write it to "company policies" and ask people to read during onboarding, the issue is small and very easy to ignore/forget.

> 
> > have a convention for adding topics to repos
> 
> Lools like [github.com/topics](https://github.com/topics/) are meant to be specific technologies for anyone on Github to explore. "DVC" would be a topic. "demo", "example", "blog" have meanings internal to Iterative so should be labels or/and prefixes.

**Comment by shcheklein** [comment] 2022-01-06 17:05
Different organization will complicate administration significantly though and potentially we'll have to pay double if at some point we'll need private repos there.

Complications like - not being able to reference a ticket from a private repo in the main org, invite everyone to two orgs, still maintain some order there.

**Comment by casperdcl** [comment] 2022-01-06 19:13
> Lools like [github.com/topics](https://github.com/topics/) are meant to be specific technologies for anyone on Github to explore.

I think (ab)using topics [like so](https://github.com/iterative?q=topic%3Aexample&type=source) to filter within an org is another use case. Seems to address:

> I don't think we can maintain a prefix policy for repositories in the long run. Even if we write it to "company policies" and ask people to read during onboarding, the issue is small and very easy to ignore/forget.

**Comment by iesahin** [comment] 2022-01-07 18:56
We discussed this with Ivan briefly, and renaming the repositories to conform to a naming convention seems feasible. Time to time, we can rake through the repos and rename those that looks example repositories. Github maintains redirections for the renames, so it shouldn't make much difference for the links. 

We can also use topics as Casper suggested for quickly sorting/grouping the repositories.

**Comment by jorgeorpinel** [comment] 2022-01-11 05:47
> (ab)using topics like so to filter within an org

Doesn't https://github.com/iterative?q=example work for this? If we're consistent enough with repo naming

Not convinced about the topics "misuse".

**Comment by iesahin** [comment] 2022-01-11 12:55
> Doesn't https://github.com/iterative?q=example work for this? If we're consistent enough with repo naming (I agree with that part). Not convinced about the topics "misuse" part.

If the above convention is used, this query won't find, e.g., ˋblog-*ˋ repositories.

**Comment by jorgeorpinel** [comment] 2022-01-27 22:06
Guys I understand there's a decision on this spike. Can we get a summary here for now? Then we can move move to either wiki or internal docs. Or close this and go there directly? Up to you @casperdcl @iesahin thanks

**Comment by casperdcl** [comment] 2022-01-28 18:47
AFAIK it's "push people to use topics on existing and new repos (and ideally create new repos using the naming convention too) as per the [the suggestion](https://github.com/iterative/dvc.org/issues/3151#issue-1094196143). Renaming existing repos low priority."

**Comment by iesahin** [comment] 2022-02-01 15:37
I've created #3245 to add topic labels to example repositories.

**Comment by iesahin** [comment] 2022-02-01 15:39
I'll move the list of example repos to the wiki, you can also copy paste from #3245 for the time being. I don't think we can push people much about this issue, but having topic labels seems a good first step.

**Comment by jorgeorpinel** [comment] 2022-02-11 06:38
No need to add a list of repos to the wiki or anywhere really if the idea is to use GH to filter them by topic. We could add the info on naming and topics to the Wiki though... Or is that internal documentation?

**Comment by iesahin** [comment] 2022-02-14 10:03
The list is meant to be generated from the topic/search some time in the future. I used it as a reference and may use it again to update the attributes.

**Comment by jorgeorpinel** [comment] 2022-02-16 00:43
OK. I'm just trying to move the decision here to wiki or internal docs so we can close the spike 🙂

**Comment by iesahin** [comment] 2022-02-17 16:13
We have added `example` topic tag for all the repositories in the list. I think we can close this for now. @jorgeorpinel

**Comment by iesahin** [comment] 2022-02-22 15:07
Closing this, as we have added `example` topic label and https://github.com/iterative?q=topic%3Aexample&type=source lists all example repositories.

**Closed by iesahin** 2022-02-22 15:07 UTC
Labels: type: discussion, dependencies
