### ISSUE TITLE
css: migrate from styled comps to plan css or css-modules

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#792] opened 2019-11-14 23:05 UTC
> Extracted from https://github.com/iterative/dvc.org/pull/776#discussion_r343969564

Our [styled components](https://www.styled-components.com/) tend to be defined after the exported component in each file (pages/, src/) so it could be confusing to find them in the JSX of previously defined components.

However we want to keep them in the bottom of each file given their strange code format. The idea then is to RENAME them so it's more obvious that they are styled components. My proposal is to simply add the name of the HTML tag they use in CamelCase. For example a `Container` component that styles a `div` tag would be renamed `ContainerDiv` and look like this in JSX.

UPDATE: Probably going for extracting and not renaming. See https://github.com/iterative/dvc.org/issues/792#issuecomment-569555264

**Comment by shcheklein** [comment] 2019-11-14 23:06
I would check if there are best practices around this. Also, would love to know @iAdramelk 's take on this.

**Comment by jorgeorpinel** [comment] 2019-11-14 23:38
I don't think styled-components.com are so used that there will be broadly established practices around it but I did look this up just now and found https://medium.com/inturn-eng/naming-styled-components-d7097950a245 where they propose using `StyledContainer` or `S.Container`, which is what Alexey suggested in https://github.com/iterative/dvc.org/pull/776#discussion_r343969564. But I still like `ContainerDiv` more. Let's just vote on it?

**Comment by jorgeorpinel** [comment] 2019-12-29 09:26
BTW if we do this and rename the `Link` styles components to something else, we should probably rename `NextLink` to just `Link` (it's natural name from [next/link](https://nextjs.org/docs/api-reference/next/link)).

**Comment by jorgeorpinel** [comment] 2019-12-29 09:26
Oh, and another option to consider for all this is to migrate to https://github.com/zeit/styled-jsx (but doesn't support nested styles I think)

**Comment by jorgeorpinel** [comment] 2019-12-29 09:27
Do you have a vote here, @iAdramelk? Thanks

**Comment by iAdramelk** [comment] 2019-12-29 12:24
@jorgeorpinel  I do think that we should probably move them to the separate files at least. I started experimenting with this approach in https://github.com/iterative/dvc.org/pull/874 (check the files in `src/Community`) and I think that this way it is a lot more convenient. We can rename them too, but if we move them to the separate files it is not that important, because it is easier to understand that they are a part of the styles. Alternatively, naming convention can be to add prefix to them. Like `SCLink` instead of `Link`. This way we will not lock ourselves in using predefined tags there and will be able to change tags without changing component names.

I checked `styled-jsx` and I am not a big fan of it, it looks janky to me. But I very much want to replace `styled-comonents` with something that not requires runtime and builds to static css files, like https://github.com/4Catalyzer/astroturf . Right now `styled-components` is making our bundle size unnecessary large and slows down pages render speed (and also make react profiling tools almost impossible to use). Alternatively, latest version of Next has added `css-modules` support so we can just switch to normal css instead (old versions of Next didn't work with normal css correctly)

**Comment by jorgeorpinel** [comment] 2019-12-30 00:16
> We can rename them too, but if we move them to the separate files it is not that important, because it is easier to understand that they are a part of the styles.

Agree. Probably no need to rename them if they're moved. I'd call the source file `styled.js` BTW (left a comment in your PR).

> add prefix to them. Like SCLink instead of Link. This way we will not lock ourselves

I don't really see the need. There's no locking since you can always rename them at import. I don't love any of the prefixes or suffixes we've suggested here anyway.

**Comment by jorgeorpinel** [comment] 2019-12-30 00:41
> I checked styled-jsx ... looks janky. But I very much want to replace styled-comonents with something ... builds to static

Well, `styled-jsx` comes from the same developers as Next.js haha...

Agree about substituting `styled-comonents` eventually, but probably needs a separate issue? Unless you think it's a high priority (cc @shcheklein) because that would basically render this and possibly other issues no-longer-relevant.

Rewriting with https://github.com/css-modules/css-modules sounds like the easiest option to me at this point, BTW. But we can list and discuss the options in a new issue if you guys agree.

**Comment by fabiosantoscode** [comment] 2020-01-16 15:36
Hey, emotion.sh is a thing.

It has all the features of styled-components, plus it can easily give you class names that you can pass to random libraries on NPM, react or not. It's more likely that you can customise a className than that you're able to control the element generation just to change a style.

Plus it has a `css` prop thing (granted, it requires a babel plugin) that allows you to define the styles right in the divs and spans and whatever which use them.

Worth a look?

**Comment by shcheklein** [comment] 2020-01-16 17:02
@fabiosantoscode @iAdramelk is migrating dvc.org to Gatsby now and probably we'll use the same convention eventually (postcss?) . @iAdramelk could shed some light here?

**Comment by iAdramelk** [comment] 2020-01-20 11:38
@fabiosantoscode thanks for suggestion, but the thing is, we didn't really need css-in-js library. We don't use any of it's advanced capabilities and in our case just importing css without the need for a runtime will be a lot better for the perfomance. The main reason why we use `styled-components` is because `next.js` can't work with plain css or `css-modules`. But we are now migrating to `gatsby `which didn't have this problem, and even if we didn't migrate, next version of `next.js` will support `css-modules` out of the box.

**Comment by jorgeorpinel** [comment] 2020-01-20 19:20
@iAdramelk @shcheklein so is this issue still valid? If the Gatsby migration is definitive, let's close it?

**Comment by shcheklein** [comment] 2020-01-20 22:49
let's keep, we'll close all the tickets with the engine label (those that will become obsolete) at once after the migration. Since it's not over, the issue is still relevant.

**Comment by shcheklein** [comment] 2020-04-09 21:42
Fixed by the recent migration.

**Closed by shcheklein** 2020-04-09 21:42 UTC
Labels: doc-website, enhancement
