### ISSUE TITLE
start: independent trails

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2496] opened 2021-05-22 17:38 UTC
UDPATE: Jump to https://github.com/iterative/dvc.org/issues/2496#issuecomment-1255510563.

## Status

* We have 5 repositories: [example-get-started][egs], [dvc-checkpoints-mnist][dcm], [get-started-experiments][gse], [get-started-checkpoints][gsc], and [get-started-pipelines][gsp].

[egs]: https://github.com/iterative/example-get-started
[dcm]: https://github.com/iterative/dvc-checkpoints-mnist
[gse]: https://github.com/iterative/get-started-experiments
[gsc]: https://github.com/iterative/get-started-checkpoints
[gsp]: https://github.com/iterative/get-started-pipelines

* We have a project that generates most of these. 

The docs use [example-get-started][egs] for:

* [Data and Model Versioning](https://dvc.org/doc/start/data-and-model-versioning)
* [Data and Model Access](https://dvc.org/doc/start/data-and-model-access)
* [Data Pipelines](https://dvc.org/doc/start/data-pipelines)
* [Metrics, Parameters, Plots](https://dvc.org/doc/start/metrics-parameters-plots)
* [Experiments](https://dvc.org/doc/start/experiments)

[Checkpoints guide][cpg] uses [dvc-checkpoints-mnist][dcm]

[cpg]: https://dvc.org/doc/user-guide/experiment-management/checkpoints

## Goals

* We want to improve the content with _minimum changes_ to the existing documents. Adding more content to the already available material is desired. 

* We want to have a common/similar project for the tutorials. A _single_ showcase project to contain all DVC features seems a bit artificial. A set of _similar_ projects may be a better tradeoff for maintenance and usability. 

* DVC has different use cases for different people and we want to emphasize these: 
** Data Versioning
** Data Access
** Sharing Models
** Presenting Models with Metrics and Plots
** Experiment Management and Sharing
** Checkpoints (which may be under "experiment management".)

* There should be more than one entry points for the tutorials, e.g., experiment management should be a first-class citizen. 

## Discussion and Research Points

* Current documentation is mostly pipelines-based. Almost all features revolve around `dvc.yaml` and the pipelines. How can we present DVC as an _experiment management system_ without first telling about the pipelines?

* How high-level the GS docs should be? We also have UC and UG documents and most of the material in GS is also relevant to these sections. Who is our audience for GS? (ML Engineers? DevOps Engineers? DS Researchers? Students? Software Engineers?) What can we assume about them? What do we want to tell them without much low-level stuff and also staying relevant? What are their daily usage patterns?

* How to evolve the example projects for each of the use cases? 

* How can we (or should we) present other relevant projects like Studio/CML/VSCode extension to people reading the GS pages?

## Decisions and Tickets

- Section name to be kept as *Get Started* for a more tutorial feeling than *Quick Start*. 
- The commands in the documents should be applicable, copy-pastable. 

### Personas that make up the audience

- Primary persona: - tech-savvy ML engineer, hands-on ML manager, industry (not students, not DevOps - or only their team asked them to check for other tools). [Comment](https://github.com/iterative/dvc.org/issues/2496#issuecomment-857401769) @shcheklein

**Comment by jorgeorpinel** [comment] 2021-05-23 03:37
Thanks for the summary, very informative.

**Pre-Q**

> [Checkpoints tutorial] uses dvc-checkpoints-mnist

Meaning https://dvc.org/doc/user-guide/experiment-management/checkpoints? Seems to use https://github.com/iterative/checkpoints-tutorial . Is that one basically https://github.com/iterative/dvc-checkpoints-mnist (`live` branch) without DVC files BTW? Cc @flippedcoder

**On the motivation for this**

> improve the content with minimum changes to the existing documents... Adding more content

Probably the most important thing and first step here would be to decide on the content. What new content are we looking to add? Which one needs changes? That should drive the sample repos (@dberenbaum has mentioned this too I think).

> should be a first-class citizen

Looks like all the existing repos are already stand-alone right? Just trying to understand whether we have a working setup or if there's some urge to keep iterating on sample repos before content. Great work so far BTW!

**On the more relevant discussion points**

> How high-level the GS docs should be?

As high-level as possible while supporting hands-on steps.

> Who is our audience for GS?

People from all backgrounds who need to learn (certain parts of) DVC fast — get a good grasp of basic concepts, problems/solutions, while trying the major commands (UX).

> can we (or should we) present other relevant projects like Studio/CML/VSCode

I'd focus on DVC for now 🙂 

<details>
<summary>Long answer</summary>
Depends on the product:
- CML isn't closely connected to GS topics as of now and has it's own GS.
- Studio we can just briefly mention and link from the Experiments docs (in GS and elsewhere).
- VSC is trickier, we can figure it out in the future (e.g. a switch between code blocks and VSC screenshots).
</details>

**Comment by shcheklein** [comment] 2021-05-25 06:56
Thanks @iesahin . I agree with @jorgeorpinel on the audience/level (I would keep it as is)/other projects (let's not do this for now- I would think about `dvclive` though). 

Some thoughts on the content (acknowledging that this is the most important one anyway).

**First, to remind a bit on why the existing example get started is considered suboptimal:**

- last sections depend on the previous ones to try to run something or even to understand them
- project doesn't fit naturally into some scenarios - e.g. checkpoint - the most obvious one
- the way it is structured it feels that data is more important than experiments, we don't trigger the feeling that DVC is not (only) about data management - it's about experiments tracking, it's about model lifecycle management, etc.

**Bottom line**: we want to make experiments (and potentially pipelines?) first class citizen in the get started. 

> How to evolve the example projects for each of the use cases?

I would not do this. I would start with two entry points - Data & Models Versioning (?), Experiments Management - something like that? 

> Who is our audience for GS?

- they know basics of Git (no need to explain what `git init` is)
- they know basics of ML (no need to spend time explaining ML itself)
- Industry folks come first, students second (but in case of GS I would try to keep comprehensible for students if they understand at least some problems we are trying to solve, know git, etc)

> What do we want to tell them without much low-level stuff and also staying relevant? 

ideally, they should understand from the GS + Use Cases where does DVC fit, how it works - high level

**Comment by shcheklein** [comment] 2021-06-06 02:55
A comment on the HN recent submission, that should drive changes to the experiments section at least:

> I have been in search of a very lightweight way to track experiments, so I went to the dvc page and was completely overwhelmed by all of the options. I tried to find the answer to a simple question — how do I log metrics and artifacts from a train/test run? I saw ‘dvc exp run’ (or something like that), but how does it know what my training script is? And what should I add to my code to checkpoint metrics or other stuff at various points in a script?
I was looking for a simple, self contained “getting started” sequence of pip installs and example code, but I found the docs linking all over the place.

> I was previously looking at keepsake, an extremely lightweight experiment tracker/logger. But it had some issues working with PyTorch lightning, so I was back searching for something else.

**Comment by iesahin** [comment] 2021-06-07 08:34
This comment is very valuable 👍🏼

**Comment by iesahin** [comment] 2021-06-08 14:18
Is there a way to get user feedback on GS pages somehow within the pages? PHP had comments in documentation maybe 10+ years ago. Could we have, for example, links to discussions, comments, or some sort of feedback facility in the pages themselves?

**Comment by shcheklein** [comment] 2021-06-08 18:26
@iesahin it's a very good point, I would love to see some nice way to collect feedback, discussions, etc. We can create a separate ticket for this and prioritize.

**Comment by iesahin** [comment] 2021-06-08 18:55
> Meaning https://dvc.org/doc/user-guide/experiment-management/checkpoints? Seems to use https://github.com/iterative/checkpoints-tutorial . Is that one basically https://github.com/iterative/dvc-checkpoints-mnist (`live` branch) without DVC files BTW?

Yes, [`checkpoints-tutorial`](https://github.com/iterative/checkpoints-tutorial) is a single branch copy of [`dvc-checkpoints-mnist`](https://github.com/iterative/dvc-checkpoints-mnist), tailored for the [UG checkpoints](https://dvc.org/doc/user-guide/experiment-management/checkpoints) guide. 

This checkpoints guide has several drawbacks, IMO: 

- It starts with setting up the pipelines and that's a distraction I think
- It uses only `dvclive` for checkpoints. There are other ways to use checkpoints with DVC API. 
- It adds the experiments/plots/metrics to the mix. These are also repeated in several other places in the docs. 

All checkpoints guides (either for the GS or UG), should assume _experiments_ as a starting point. Checkpoints rely on `dvc exp` and without experiments, checkpoints are not useful. We need to tell checkpoints as an _extension_ to the experiments. 

The reason I proposed #2518 is this. There should be GS level guide _after_ experiments that introduce the checkpoints.

**Comment by iesahin** [comment] 2021-06-08 19:04
> What new content are we looking to add? Which one needs changes? That should drive the sample repos

I'd rather have an _evolutionary_ approach in these. What's the most obvious, glaring points that we miss from the Get Started section? 

* We don't have a full and independent experiments tutorial, that doesn't rely on pipelines. 
* We don't have any practical, hands on information on checkpoints. 
* Metrics and plots should be told as a product of _experimentation._ 

I propose three starting points for the GS docs: 

* Data and Model Versioning and Access
* Pipelines 
* Experimentation

These 3 documents should be _independent_ from each other. They can have subsections that we use to link from each other. Each should take at most ~1 hour to read and understand the subject matter.

**Comment by iesahin** [comment] 2021-06-08 19:34
> Looks like all the existing repos are already stand-alone right? Just trying to understand whether we have a working setup or if there's some urge to keep iterating on sample repos before content.

Example repos are actually shaped by the tutorial and showcase requirements. The reason I'm trying to bring forward a GS Experiments document in #2497 is to shape the repository in iterative/example-repos-dev#44 according to the reviews. I've updated, e.g., almost all the parameters, the pipeline, etc. in `get-started-experiments` after review in #2497. We can create, destroy, split, merge the repositories as much as we like.

These `get-started-X` repositories will be shaped as we progress in the docs. They are more fluid and disposable than the current one.

**Comment by iesahin** [comment] 2021-06-08 19:36
> > How high-level the GS docs should be?
> 
> As high-level as possible while supporting hands-on steps.

What do you mean by _high level_ exactly? @jorgeorpinel 

I have some ideas but would like to learn yours first.

**Comment by iesahin** [comment] 2021-06-08 19:49
> > Who is our audience for GS?
> 
> People from all backgrounds who need to learn (certain parts of) DVC fast — get a good grasp of basic concepts, problems/solutions, while trying the major commands (UX).

IMHO _all backgrounds_ is a set, a bit too large. We need to profile the users and decide on their goals to use DVC. 

We need to make assumptions on the following criteria (and more)

- Do they know to write software? (in any language)
- Do they know Python?
- Do they know Git?
- Do they know to use text editors?
- How comfortable are they using the command line?
- What is their OS?
- Are they working locally or remotely?
- Do they use cloud services?
- How large are their organization? Are they working solo or within a 10000 people corporation?

The most important: What they ask from DVC?
* Dataset tracking
* Experiment management
* Model tracking
* Sharing experiments within their organization
* Building demos
* Automated pipelines

I'd like to have 3-5 distinct persona, for whom we write our content. We can review the documents in their eyes. Without a set of concrete persona, I think content production becomes a moving target. I can write for myself and you can review for yourself but our goal is not to document the software for ourselves.

**Comment by iesahin** [comment] 2021-06-08 19:52
> > can we (or should we) present other relevant projects like Studio/CML/VSCode
> 
> I'd focus on DVC for now

I think presenting visual aspects using Studio is much easier _at first._ For example using plots and showing how those plots are generated in DVC seems easier to follow than showing a bunch of commands and telling the end result.

**Comment by iesahin** [comment] 2021-06-08 20:04
> > How to evolve the example projects for each of the use cases?
> 
> I would not do this. I would start with two entry points - Data & Models Versioning (?), Experiments Management - something like that?

Then, it looks like we can use `example-get-started` for  _Versioning_, and use the current documentation as a _chapter_ for _Versioning_ docs. It will contain (1) Data and Model versioning (2) Data and model access (3) Sharing and Remotes. 

Write another document for _Experiments_, that contain (1) Experiment Management (2) Plots and Metrics, (3) Sharing Experiments, and (4) Checkpoints. 

Readers may start from Versioning and proceed to Experiments, or start from Experiments and hop to Versioning. 

I think we need another one for the Pipelines, or write the pipelines as an addendum to each of these. Pipelines are a bit orthogonal to the other aspects.  

I would like to read/tell one thing at a time, in each section. So adding pipelines to the mix may reduce the overall focus for the documents. We can have a shorter _Pipelines_ document that we link from each of these.

**Comment by iesahin** [comment] 2021-06-08 20:12
> * they know basics of Git (no need to explain what `git init` is)
> 
> * they know basics of ML (no need to spend time explaining ML itself)
> 
> * Industry folks come first, students second (but in case of GS I would try to keep comprehensible for students if they understand at least some problems we are trying to solve, know git, etc)

I think I can create 3 distinct profiles from these: (1) an industry person with Git knowledge looking for ML production tools, (2) a graduate student with ML experiments looking for experiment tracking, (3) a DevOps guy working in an ML environment with lots of data. If we can keep these profiles as distinct as possible while making their _union_ cover our user base, we can check the docs in these profiles' eyes and see the omissions easily. 

I need to have some direction here about the typical users.

**Comment by iesahin** [comment] 2021-06-08 20:19
BTW, I'm using some ideas from [Martin Lindstrom's Small Data](https://www.amazon.com/Small-Data-Clues-Uncover-Trends-ebook/dp/B012N6FB84) about this profiling thing. I read the books a few years back and I remember how he produces marketing material using profiling. I remember the book saying there are a _finite number of profiles_ that we should be thinking about and people belong to these categories, instead of each having a unique character.

**Comment by jorgeorpinel** [comment] 2021-06-09 00:37
> would love to see some nice way to collect feedback

Annoying "randomly selected" popups!

![image](https://user-images.githubusercontent.com/1477535/121272746-5b706000-c88c-11eb-80d5-33e43dc6aeff.png)

**Comment by jorgeorpinel** [comment] 2021-06-09 00:37
@iesahin 

> We don't have a full and independent experiments tutorial, that doesn't rely on pipelines.

Get Started pages are not tutorials. (See "Master Dict" in https://www.notion.so/iterative/wip-Lost-in-Translation-17a263187e2b40e88072ce041a5be4e1)

> We don't have any practical hands on information on checkpoints.

https://dvc.org/doc/user-guide/experiment-management/checkpoints and https://github.com/iterative/dvc-checkpoints-mnist (linked from a few places)

> https://dvc.org/doc/start/metrics-parameters-plots

This is a good point. But it's hard for me to envision combining both topics since there's so much material in https://dvc.org/doc/start/metrics-parameters-plots

> Data and Model Versioning and Access

I think it makes sense to keep Access separate though.

> Each should take at most ~1 hour to read and understand the subject matter

This is a good Q. I don't think we've measured the read/try time before. I'm hoping it's much less than 1h — not sure that qualifies as "quick" (assuming Get Started = Quick Start).

> we can employ Studio in several places
presenting visual aspects using Studio is much easier at first

Studio is a separate product and has it's own docs. I can see adding a layer to switch from terminal to studio in many examples but again, I wouldn't further complicate this discussion with that for now.

> > As high-level as possible while supporting hands-on steps.
>
> What do you mean by high level exactly? @jorgeorpinel

Great Q actually. By high-level I understand that the GS will cover all of DVC features but only enough to establish what main problem/solution they represent. In this sense it's a relatively shallow kind of doc.

Again, it's goal is to cover lots of ground quickly, provide an overall impression, basic UX experience, and awaken curiosity (link to guides, refs, etc. for more deets).

> IMHO all backgrounds is a set, a bit too large.

I don't think it's too broad. People will filter themselves out. If you intentionally ended in the GS, you probably have a good reason, and fit our target audience.

> I'd like to have 3-5 distinct persona, for whom we write our content.

Sounds good but I think the GS is the one place where we may not need to worry about that too much. Let's make a separate issue or discuss separately? (I have a metadoc about this [here](https://www.notion.so/iterative/Audiences-ccb7abb9a198476aa0c01581479c5eaf))

**Comment by shcheklein** [comment] 2021-06-09 05:56
A lot of information there :)

I think Emre you are right about 3 entry points. Since we have 2 (mixed now into get-started), I would focus first on the 3rd one - experiments management.

Primary persona for that one - tech savvy ML engineer, hands-on ML manager, industry (not students, not DevOps - or only their team asked them to check for other tools). It doesn't mean that we should disregard simplicity. But we should not be educating people on how to use git.

Level: the purpose of get started is to have a document that people can get idea really quick from. It's more like a quick start. Thus - simple commands, hiding long explanations, etc.

**Comment by iesahin** [comment] 2021-06-09 09:16
> Get Started pages are not tutorials.

[Here](https://www.notion.so/iterative/Get-Started-46255d1671244f50ba97d6d635e675a4) there is also a `Tutorial` tag and I think, _Quick Start_ and _Get Started_ are two different kinds. "Get Started" reads like you're about to start something _big_ and these are the _first steps._ "Quick Start" is saying _you're starting these quickly and can possibly walk the rest by yourself._ Get Started feels like _let's start and we'll walk together_, it doesn't say anything that we'll finish that walking or not. 

I'd rather rename the sections like (1) Quick Start to Data Management (2) Quick Start to Experiment Management (3) Quick Start to Pipelines and have at most 3000 words for each. (~10 minutes reading.) Another 20 minutes for trying commands and in around 30 minutes, the user should get a gist of the subject.

**Comment by iesahin** [comment] 2021-06-09 09:19
> This is a good Q. I don't think we've measured the read/try time before. I'm hoping it's much less than 1h — not sure that qualifies as "quick"

I think, yes, ~1 hour is too much. Aiming for a soft limit of 10 minutes / 3000 words is better, probably.

**Comment by iesahin** [comment] 2021-06-09 09:28
> > What do you mean by high level exactly? @jorgeorpinel
> 
> Great Q actually. By high-level I understand that the GS will cover all of DVC features but only enough to establish what main problem/solution they represent. In this sense it's a relatively shallow kind of doc.

This is more or less what I understand too, but I think we should aim for 80% of the features that _our user_ may need in their day to day activities. Instead of presenting DVC features, we should be thinking about which commands they use most and in what order. Once they started, they can come back and read the UG for details or other features.

**Comment by iesahin** [comment] 2021-06-09 09:33
> I don't think it's too broad. People will filter themselves out. If you intentionally ended in the GS, you probably have a good reason, and fit our target audience.

I think we need to control who filters themselves out. If we don't want some kind of audience, e.g., managers who never saw a command line before, filtering out is fine. But, if someone who might be within our users filter themselves out, IMO that's not OK. _Let's throw all features to the wall and see which users stick themselves to it_ may not be a good strategy here.

**Comment by iesahin** [comment] 2021-06-09 09:37
> Again, it's goal is to cover lots of ground quickly, provide an overall impression, basic UX experience, and awaken curiosity (link to guides, refs, etc. for more deets).

This goal and _presenting all DVC features_ might contradict time to time, and in that case I'd prefer this ⬆️ goal for GS and _presenting DVC features_ in UG.

**Comment by iesahin** [comment] 2021-06-09 09:43
> > I'd like to have 3-5 distinct persona, for whom we write our content.
> 
> Sounds good but I think the GS is the one place where we may not need to worry about that too much. Let's make a separate issue or discuss separately?

Notion document seems fine for discussion, but I don't believe that's not important. GS docs are the most restrictive place we have to think about the audience I think. It's like a _glass shop window_ where you present your most interesting items. We have a limited space and we need to think about who might stop and take a look to these items.

**Comment by iesahin** [comment] 2021-06-09 09:50
> the purpose of get started is to have a document that people can get idea really quick from. It's more like a quick start. Thus - simple commands, hiding long explanations, etc.

I think we should rename the section to Quick Start if it's _more like_ a quick start. "Get Started" has a "tutorial" feeling and that changes the focus to more in-depth explanations and detailed commands I think.

**Comment by jorgeorpinel** [comment] 2021-06-10 02:44
> we should aim for 80% of the features that our user may need in their day to day

Agree. I meant major features, e.g. we don't even mention the run-cache (I think). Your criteria ☝️  is much better described.

>  docs are the most restrictive place we have to think about the audience

TBH Idk, it's not something we've been able to structure much so far. And we seem to be doing OK. But yes ideally we should get there and there's a corresponding direction in the [roadmap].

[roadmap]: https://www.notion.so/iterative/8165634376f040ae83200ff9138a1755?v=d1ec7ed863e24cf8a16090f62efac06d

**Comment by jorgeorpinel** [comment] 2021-06-10 02:45
_Looks like everything else we discussed in person so I assume no need to further discuss the other points._

**Comment by iesahin** [comment] 2021-06-10 09:26
Yesterday, in the meeting @shcheklein said the initial name for this section was *Quick Start* and was listing a bunch commands. Users wanted more hands-on, applicable, copy-pastable commands and the section evolved to its current form. 

We decided to keep *Get Started* structure as is. 

We decided to write a new Experiments section instead of the ongoing #2497.

**Comment by iesahin** [comment] 2021-06-15 11:54
I began to work with mind maps/concept maps/tree diagrams for this spike. I don't know if you can open [this link](http://www.xmind.net/m/ViBdNw) but we can discuss these in the meeting. A proposal for a new structure for the GS documents is like:

![DVC Get Started](https://user-images.githubusercontent.com/476310/122047537-f1563e80-cde8-11eb-8025-15d552010d14.png)

**Comment by shcheklein** [comment] 2021-06-16 01:31
I like the term "Trail"!

Some parts look a bit too complicated (e.g. trying to cover all possible ways of doing checkpoints).

**Comment by jorgeorpinel** [comment] 2021-06-16 02:16
Great map! The intention seems pretty exhaustive, may be good for https://github.com/iterative/dvc.org/issues/144#issuecomment-844711839 first, and then extract a minimal section for the GS.

Note that over there we have a _ML Model Optimization_ "trail" but that may overlap with Experimentation. Perhaps the missing one (if any) is Pipeline/Model Deployment (intro to MLOps).

**Comment by iesahin** [comment] 2021-06-16 08:11
> Some parts look a bit too complicated (e.g. trying to cover all possible ways of doing checkpoints).

I'll remove some parts or merge them to others. `dvc freeze` is another such example. I'm thinking to apply "80% rule" we discussed above to each.

**Comment by iesahin** [comment] 2021-06-16 08:23
I used to term *trail* because I think to link the sections from these as *next steps.* Reader may follow a predefined trail, or hop from one section in experimentation to a section in data management. I think to link these sections like a [Gamebook](https://en.wikipedia.org/wiki/Gamebook). 

@shcheklein @jorgeorpinel

**Comment by jorgeorpinel** [comment] 2021-06-17 00:07
> I'm not sure if we can reach a conclusion in #144 in general. This structure can be applied to UG as well

Yep I'm referring to the UG mainly. Specifically the 3-4 subsections we discussed in https://github.com/iterative/dvc.org/issues/144#issuecomment-844711839

> used the term trail because I plan to link the sections from these as choose your next step

These are great ideas but I have to say, we seem to continue expanding the possible plan with alternatives, without having an obvious list of next steps (at least I'm not clear on what that may be). Can we balance this process somehow? Maybe we can first focus on one or two of the MD docs you've generated base on this map so far (briefly seen in the docs meeting), e.g. in the form of 1-2 draft PRs.

**Comment by iesahin** [comment] 2021-06-22 09:31
This is a new map modified before/after the meeting with @dberenbaum yesterday: www.xmind.net/m/GmcEzB

It also contains the current structure and links.

**Comment by shcheklein** [comment] 2021-09-27 19:42
Since. we are getting to the trails structure now, I want to step back a bit and discuss it before we jump into restructuring things. Would love to hear your opinions here.

I like to think about trails (and see it's not exactly what Emre has in his mind map) as a way to present _all_ DVC functionality within _each_ trail. The only difference is the focus, where do we start in each trail. E.g. for experiments - we start by focusing on rapid iterations and gradually come for data management (explain `dvc add` - all of that). Another example - existing get started - it's a "data management" trail. It starts with `dvc add` and ends in experiments - but it covers all the things more or less.

If we don't do that then I'm not sure what will be so different compared to what we have now? We'll have even more sections, and people will have to go through all three trails to get the full picture.

Or do you think we can keep them simpler and done in a way that you can start from any of three, and switch to another after and it can feel natural?

**Comment by dberenbaum** [comment] 2021-09-27 20:01
> I like to think about trails (and see it's not exactly what Emre has in his mind map) as a way to present _all_ DVC functionality within _each_ trail. The only difference is the focus, where do we start in each trail. E.g. for experiments - we start by focusing on rapid iterations and gradually come for data management (explain `dvc add` - all of that). Another example - existing get started - it's a "data management" trail. It starts with `dvc add` and ends in experiments - but it covers all the things more or less.

My first impression is that the middle ground might be useful. We could include links and mentions to other trails and features without going into detail about them.

> If we don't do that then I'm not sure what will be so different compared to what we have now? We'll have even more sections, and people will have to go through all three trails to get the full picture.

Right now, each section builds on the previous section, so someone who wants to experiment needs to first go through several sections about data management and pipelines, which might not matter to them.

**Comment by jorgeorpinel** [comment] 2021-09-28 02:47
Having not been involved here for a while I want to say that that's more or less what I intuitively understood by trails too: each one has a different focus (one for data mgmt, one for mlops, etc.) but they overlap significantly. I didn't think they all cover all of DVC's features though -- that sounds like too much -- but mainly the ones relevant to the trail and those from other feature layers that are important or closely related as well.

But thinking about now, it I'm not sure this plan is great for "the Get Started" (if we think of it as a single, quick-start guide), since each trail can be pretty long and require several chapters in itself. But if we implement this almost as a switch in the GS then it may start making more sense. Perhaps even if we can have modules and recombine them into a single page (new docs engine feature).

**Comment by dberenbaum** [comment] 2021-09-29 19:38
I don't think we need to be so abstract since we have #2574 as a concrete example. Does this doc need to cover more about data management and pipelines? Or does there need to be some additional next steps doc? If anything, I hope we can remove even more about data management and pipelines from the doc once we introduce `dvc exp init`.

> Another example - existing get started - it's a "data management" trail. It starts with `dvc add` and ends in experiments - but it covers all the things more or less.

I thought that one advantage of the trails was to make the get started docs shorter and less intimidating. It's not clear at first glance how far users are supposed to go. Also, if they come back later to learn about experiments, I'm not sure it will be clear whether they should continue on the data management trail or start on the experiments trail. If they do want to continue on the data management trail, they have to get through pipelines first, even if that's of little interest.

This relates to the personas mentioned by @iesahin. Is the persona for data management someone who wants to eventually have a solid understanding about all core features of dvc, or are they only interested in starting to version data?

**Comment by shcheklein** [comment] 2021-09-30 04:29
> I thought that one advantage of the trails was to make the get started docs shorter and less intimidating.

I never had in mind a problem of docs length or their complexity in mind (but agree that each trail should be simpler than the existing get started that covers too much at once too deep).

I think the primary goal for me was to create an independent entry point for the experiments. And it should be clear that you can start reading from it (w/o reading all the previous parts), you follow the trail and you get a good overview of DVC. In the experiments trail It would natural for me to see metrics, plots next. Also how to manage data (we can say that data is an essential part of experiments, also that artifacts go into cloud), then `dcv machine` when it's ready. 

I think we are on the same page here, and it's not a blocker of PR (though we need to fix it, it's not ready to be merged) - it should not be repeating the same stuff and should not be on the same level of details. I wish we have good connections, expandable sections with good references, etc - so that people do not feel lost and can read briefly about basics, have an idea about what can they read next.

**Comment by jorgeorpinel** [comment] 2022-01-14 07:13
Is this still a SPIKE?

**Comment by jorgeorpinel** [comment] 2022-01-14 07:13
and "researching" status?

**Comment by iesahin** [comment] 2022-01-14 14:24
More or less, yes.

**Comment by jorgeorpinel** [comment] 2022-01-14 17:34
Maybe it's a discussion instead? Spikes typically have short timeframes I think. Anyway. Some sort of summary of the moves and decisions so far could be interesting to see. As it is the issue is really large and hard to figure out.

**Comment by iesahin** [comment] 2022-01-15 13:38
I would like to review this time to time. The researching/spike part is mostly done, or has other related tickets but I feel the discussion here is important. 

Removing the "spike" label. It can be closed after labeling with a suitable tag for later review as well.

**Comment by jorgeorpinel** [comment] 2022-03-30 07:54
Alright we need a summary of this please @iesahin . Is https://github.com/iterative/dvc.org/pull/3050 all that's missing to get to a first milestone here?

What else is left and can we consolidate (ideally into a new issue) with #1943 and #2474? That would be really helpful to get a sense of where we are with the GS and what a future milestone may look like.

--

On the "trails" idea, as discussed offline we should probably keep a plain, curated structure for the Get Started so no need to decompose into these atomic doc units that can be reorganized into many trails. We could however use that strategy for the User Guide, where a complex structure like that could actually result beneficial! Related to #144 and #3128 -- let's move that discussion there?

**Comment by jorgeorpinel** [comment] 2022-04-11 23:32
UPDATE: From call with @iesahin we agreed he'll submit a proposal (draft PR?) that reorganizes existing GS content as-is (with possible overlap/repeated sections) into 3 or 4 simple use-case-based "tails" (instead of the 5 feature-based pages we have now). We didn't specify which basic usage cases but here are my suggestions:

- Easy ML experimentation (`dvc exp` + visualization)
- Separate data from code (cover data management + versioning)
- Codifying modeling (data pipelines & metrics)

WDYT?

**Comment by shcheklein** [comment] 2022-04-11 23:52
I think we are complicating this a bit again. We clearly have two projects, two logical trails at the moment, and I would go with a simple restructuring around those two - Data and Experiments.

**Comment by jorgeorpinel** [comment] 2022-04-12 00:42
Sure, those were just initial suggestions to get feedback. Just Data and Experiments sounds good to me. It may be a bit harder to just reuse most of the existing content without much editing to merge 5 pages into 2 (and not end up with very long tutorials) but we can try and see how it looks. The idea is that this draft/proposal shouldn't take too much effort, maybe a day or 2.

**Comment by shcheklein** [comment] 2022-04-12 00:47
>  It may be harder to keep all of the existing content with only minor editing to merge 5 pages into 2

why do we have to merge it? :) just keep it as-is.

**Comment by jorgeorpinel** [comment] 2022-04-12 22:04
Ok yeah that's an easy first step. Not sure what it achieves... Let's see what @iesahin comes up for now!

**Comment by jorgeorpinel** [comment] 2022-06-20 23:02
https://github.com/iterative/dvc.org/issues/3678 could be part of this too.

**Comment by jorgeorpinel** [comment] 2022-09-22 18:49
@shcheklein @dberenbaum going back to https://github.com/iterative/dvc.org/issues/2496#issuecomment-1095692848 (and following answers): should we separate most of the contents of [Data Pipelines](https://dvc.org/doc/start/data-management/data-pipelines) (and maybe metrics, etc.) into a different trail? I.e. can we prioritize https://github.com/iterative/dvc.org/issues/2857 now?

This would include creating some new content as well as simplifying the existing one keeping in mind the original goal of having "trails": each one is comprehensive i.e. it covers all the major features of DVC appropriate for that point of view (even if there's some repetition).

**Comment by jorgeorpinel** [comment] 2022-09-22 19:02
Wrt to the original title/intention of the OP:

> Improving Projects and Tutorials
We have 5 repositories: example-get-started, dvc-checkpoints-mnist, get-started-experiments, get-started-checkpoints, and get-started-pipelines.

I think now we use [dataset-registry](https://github.com/iterative/dataset-registry) for data versioning, https://code.dvc.org/get-started for pipelines, and nothing for experiments.

Do we need any more? Who owns the existing example repos now? (Should we involve CSE?)

**Comment by dberenbaum** [comment] 2022-09-22 20:23
IMHO we shouldn't spend much more effort on get started trails right now because:
1. The trails aren't that independent right now (for example, you still need data versioning and pipelines for experiments today), and until we solve that on the product side, I'm not sure having separate docs trails helps.
2. It can actually be more intimidating and confusing for users since they have to make a choice up front of what to choose without having a good understanding of what the differences are.
3. Making each trail "comprehensive" might reduce the reader's burden to choose the right trail, but I also think it can add confusion (why does this talk about pipelines when I intentionally chose to only get started with data management?) and may end up being burdensome to develop and maintain.
4. Each trail seems expensive to develop relative to other docs work. It requires developing an entirely separate project repo. In general, the value of get started probably makes it worthwhile, but not sure it's currently a good use of resources to develop more of them.
5. A lot of effort has already been spent on get started over the last year or so. I worry we are moving things around without adding much value at this point.

**Comment by jorgeorpinel** [comment] 2022-09-23 23:27
OK @dberenbaum, thanks for the detailed reasoning and I mostly agree with you. Just for the record though, here's what @shcheklein and I discussed would be the top problems with the current GS trails:

- Experiments: not very meaningful example repo (we need a deep learning project, more or less easy to run) [difficulty: hard] -- work with CSE?
- Data Mgmt: doesn't cover enough topics e.g. data registry, shared cache [difficulty: medium-low]
- Pipelines: new trail needed with different approach ([vs DM/DP](https://dvc.org/doc/start/data-management/data-pipelines)) e.g. migrate from Jupyter [difficulty: medium-high]

> expensive to develop ... an entirely separate project repo

Yes but that's pretty much the blocker/ critical task at this point.

> not sure it's currently a good use of resources

That depends on what other things we can do. For now I think indeed there's lower hanging fruit of similar impact like following up on https://github.com/iterative/dvc.org/issues/144#issuecomment-1206648437 and https://github.com/iterative/dvc.org/issues/3833 but we can also start organizing and planning the wider team to address some of the above problems.

**Comment by shcheklein** [comment] 2023-03-01 03:17
Closing this, we have done the first part - split into two trails and we can back to this later when we need the next iteration (e.g. on pipelines).

**Closed by shcheklein** 2023-03-01 03:17 UTC
Labels: A: docs, ✨ epic, C: start
