### ISSUE TITLE
ug: migrate `contributing/blog`

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#3889] opened 2022-08-22 09:26 UTC
### Report

We have now migrated blogs to iterative.ai and also there is a new DVC way of adding images. We should be updating the https://dvc.org/doc/contributing/blog page.

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/3889#issuecomment-1222559504

**Comment by RCdeWit** [comment] 2022-08-22 10:25
Just went through the process of adding images to the DVC remote. I think the new page/guide should detail these steps quite clearly. The relevant information is currently scattered across `contributing/blog`, the `iterative.ai/README.md`, and `itops/utils`.

I managed to get everything working, but I don't think I could have done so in my first week. Whereas the process for contributing to the blog is an essential part of the DevRel onboarding.

Steps that I think are worth clarifying in the updated guide:
- You need to set your AWS credentials for the production environment with `aws configure` (mine were set for sandbox).
- Where to find the `blog` and `uploads` folder
- Order of `dvc` and `git` commands for commits (DVC basics, but just to be sure).

Also, with the blog being moved away from dvc.org, should this still be a page here? Or would it be better to move elsewhere?

**Comment by jorgeorpinel** [comment] 2022-08-24 20:51
Hi. So is https://github.com/iterative/dvc.org/issues/1115 solved?

**Comment by shcheklein** [comment] 2022-08-24 20:53
Not for this repo I guess :)

**Comment by rogermparent** [comment] 2022-08-24 21:49
Seems #1115 is technically about docs, but informally most discussion around the issue is about the blog since the blog has more images _by far_.

We could leave this up until we give dvc.org's docs (and assumedly all the others) the same treatment, but that issue is much lower priority than doing it for the blog which lies entirely in iterative.ai now so there's an argument for transferring #1115 to iterative.ai and closing it.

**Comment by jorgeorpinel** [comment] 2022-08-25 01:50
> we should move all docs to the README in the (iterative.ai) repo

Agree, BTW. We can just remove https://dvc.org/doc/contributing/blog (redirect to README) and expand on https://github.com/iterative/iterative.ai#adding-image-for-blogs.

> most discussion around the issue is about the blog

Yes, that was my assumption. I didn't think these websites (nor the docs engine parts) need a special image hosting solution like for blogs. If we agree on that then I'd close #1115.

**Closed** 2022-11-18 03:21 UTC
Labels: A: docs, C: guide
