### ISSUE TITLE
support external links on the sidebar (quick fix)

### ISSUE THREAD

**Issue by rogermparent** [iterative/dvc.org#1272] opened 2020-05-08 21:41 UTC
This issue is specifically to allow for external links on the current sidebar setup. 
There are plans to renovate the sidebar code entirely, but it's worth fixing this issue in the current set-up because making a real sidebar overhaul may take a little while.

**Comment by shcheklein** [comment] 2020-05-08 21:49
Related #897 #515

**Comment by jorgeorpinel** [comment] 2020-05-09 01:25
This looks like a duplicate of #897 essentially, bc/ hat's our only use case rn I think.

**Comment by jorgeorpinel** [comment] 2020-05-09 01:26
OK never mind I see a PR was also created so that's fine. @rogermparent keep in mind that if you're sending the PR right away you could sometimes skip creating the issue too 🙂

**Comment by shcheklein** [comment] 2020-05-09 02:41
@jorgeorpinel for the record, I asked Roger to create the ticket for visibility and since all other tickets are more content focused rather than engine. So, I thought that it would be beneficial to have an engine one :)

**Closed** 2020-05-09 02:52 UTC
Labels: doc-engine, enhancement, priority-p1, website
