### ISSUE TITLE
dvc get step asks for github password

### ISSUE THREAD

**Issue by deepakdeore2004** [iterative/dvc.org#5329] opened 2024-11-28 05:02 UTC
### Report

`dvc get` asks for github password while following https://dvc.org/doc/start/data-pipelines/data-pipelines#setup 

```
$ dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
Cloning dataset-registry|                                                                                                                                        |0.00/? [00:00,      ?obj/s]Password for 'https://9ab5f4041af6dfd497cc1a6076ee5dc2ae617165@github.com':
ERROR: failed to get 'get-started/data.xml' - SCM error: Failed to clone repo 'https://github.com/iterative/dataset-registry' to '/var/folders/01/8sgnlrs93mjd7p0jnfnvfbn40000gp/T/tmpons9g0nadvc-clone': No valid credentials provided
```

**Comment by shcheklein** [comment] 2024-11-28 19:36
@deepakdeore2004 I can't reproduce it. Are you using some specific Git config? E.g. you are providing user name and password in some way there? I see `9ab5f4041af6dfd497cc1a6076ee5dc2ae617165` - where does it come from? 

can you check if you have some credentials helper set? `credential.helper` via `git config --list` for example?

are you using some specific environment?

(closing for now, but please feel free to add more details - it just doesn't look lie a bug atm)

**Closed by shcheklein** 2024-11-28 19:36 UTC

**Comment by deepakdeore2004** [comment] 2024-11-29 05:23
thanks for the pointer, some stale config was present with expired token in .gitconfig that caused the issue
