### ISSUE TITLE
add Windows mode to the documentation examples

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc.org#134] opened 2018-12-08 19:15 UTC
There was recently an issue raised at the community channel related with the way Windows handle paths / interprets slashes; it ocurred while reading the tutorial, so I'm assuming there's no clear awareness of Windows's shell on the docs.

**Comment by shcheklein** [comment] 2019-02-23 01:55
Ideally I think next step should be to implement a switch for the documentation - to show Windows/Linux mode.

**Comment by jorgeorpinel** [comment] 2019-11-25 05:32
BTW #759 is a duplicate of this. But there's more info over there so I'll close this one. Thanks

**Closed by jorgeorpinel** 2019-11-25 05:32 UTC
Labels: docs, enhancement
