### ISSUE TITLE
lint: resolve errors in pages/ and update lint target

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#716] opened 2019-10-20 21:52 UTC
UPDATE: See latest known state in https://github.com/iterative/dvc.org/issues/716#issuecomment-549693282.

**Comment by jorgeorpinel** [comment] 2019-10-21 15:24
Unrelated:

> npx eslint pages

@algomaster99 notice that we've officially migrated to using `yarn` due to some weird `npm install` behavior on different platforms.

**Comment by jorgeorpinel** [comment] 2019-10-21 15:25
See https://dvc.org/doc/user-guide/contributing-docs

**Comment by shcheklein** [comment] 2019-10-21 17:59
we should also update the `yarn lint` target to include `pages` cc @iAdramelk

**Comment by algomaster99** [comment] 2019-10-22 09:16
@jorgeorpinel 

> notice that we've officially migrated to using `yarn` due to some weird `npm install` behavior on different platforms. See https://dvc.org/doc/user-guide/contributing-docs

Using `npx` won't make a difference because `npx` just runs the script in a node environment.

**Comment by iAdramelk** [comment] 2019-10-23 03:47
@algomaster99 not exactly. `npx` will check if `eslint` installed and, if not, will install it globally and run it from there. In current case there is not difference because we have eslint in `node_modules/.bin`, but in some cases it can lead to unexpected behavior, like script running even if there is no required dependencies in `package.json` or script reinstalling itself on every run of CI.

**Comment by jorgeorpinel** [comment] 2019-11-05 07:12
Updated output of `eslint src pages`:

```
/Users/drbidibombom/dvc.org/pages/_document.js
   3:8   error  'Router' is defined but never used                    no-unused-vars
  12:3   error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  19:27  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  27:7   error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  28:9   error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  28:9   error  <html> elements must have the lang prop               jsx-a11y/html-has-lang
  29:11  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  30:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  31:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  32:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  33:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  38:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  43:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  46:1   error  This line has a length of 206. Maximum allowed is 80  max-len
  48:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  53:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  54:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  58:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  60:1   error  This line has a length of 206. Maximum allowed is 80  max-len
  62:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  64:1   error  This line has a length of 97. Maximum allowed is 80   max-len
  66:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  71:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  76:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  82:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  88:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  95:11  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  96:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope
  97:13  error  'React' must be in scope when using JSX               react/react-in-jsx-scope

/Users/drbidibombom/dvc.org/pages/features.js
   20:16  error  Component definition is missing display name                     react/display-name
   68:24  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities
   68:34  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities
  183:1   error  Unexpected tab character                                         no-tabs

/Users/drbidibombom/dvc.org/pages/index.js
  32:16  error  Component definition is missing display name                                                                                                                                                                                                                                                                                                                             react/display-name
  37:7   error  Anchors must have content and the content must be accessible by a screen reader                                                                                                                                                                                                                                                                                          jsx-a11y/anchor-has-content
  37:7   error  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

/Users/drbidibombom/dvc.org/pages/support.js
   22:16  error  Component definition is missing display name         react/display-name
   52:19  error  <iframe> elements must have a unique title property  jsx-a11y/iframe-has-title
  160:1   error  Unexpected tab character                             no-tabs

✖ 39 problems (39 errors, 0 warnings)
```

**Comment by jorgeorpinel** [comment] 2019-11-05 17:54
I'm working on the above ^ but

> and update lint target

@algomaster99 @shcheklein don't you think we should in fact only lint staged changes, the way Prettier is ran also? I think this project allows that for ESLint: https://github.com/okonet/lint-staged

**Comment by jorgeorpinel** [comment] 2019-11-05 19:32
> I would say we def should run the full pass on the CI side. As for the pre-commit hook - we can do only staged, probably.

Yep, that's how we do it with the formatter (Prettier). Will work on it.

**Comment by iAdramelk** [comment] 2019-11-06 09:04
Yep. We are using lint-staged in blog already: https://github.com/iterative/blog/blob/master/package.json#L16-L35 Can as well use it here too. But we should probably switch tslint to lint-staged too.

**Comment by jorgeorpinel** [comment] 2019-11-06 17:17
Already applied in #761, please check there.

> we should probably switch tslint to lint-staged too.

What do you mean? I don't think we use TS or tslint in this project.

**Comment by iAdramelk** [comment] 2019-11-07 02:34
@jorgeorpinel sorry, my bad. Mixed projects inside my head. Was thinking about `prettier` and `pretty-quick`. `pretty-quick` is doing pretty much what `lint-staged` is doing for other linters

**Comment by jorgeorpinel** [comment] 2019-11-07 03:50
Good point. We're using both `pretty-quick` and `lint-staged` now. We should probably migrate Prettier from the former to the latter? cc @algomaster99

**Comment by algomaster99** [comment] 2019-11-08 20:20
@jorgeorpinel Can you tell me what has to be done? :smile:

**Comment by jorgeorpinel** [comment] 2019-11-08 22:10
Actually let's wait til #776 is merged, sorry for unnecessary tag Aman. I just remembered you initially implemented the current `pretty-quick` solution so thought you may be interested in updating it to `link-staged`. But again, wait because I may implement it myself in #776 😋

**Comment by jorgeorpinel** [comment] 2019-11-14 04:28
@algomaster99 I tried moving from `pretty-quick` to `lint-staged` in #776 but it's not that simple so I'm abandoning that goal for now haha. Would you like to try after all? I extracted #788 for this so feel free to self-assign over there.

**Closed** 2019-11-14 22:48 UTC
Labels: docs, engine, good first issue, hacktoberfest, priority-p1
