### ISSUE TITLE
add HDFS documentation

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#50] opened 2018-07-15 12:13 UTC
Moved from https://github.com/iterative/dvc/issues/766

**Comment by shcheklein** [comment] 2019-03-25 06:41
@dmpetrov @efiop Need to specify more info of what's missing. How is related to Dask (remote SSH) computation. Is it about writing a guide or just mentioning very specific to HDFS things across different command references, get started, etc?

**Comment by dmpetrov** [comment] 2019-03-25 07:15
@shcheklein it looks like hdfs workspace checkout  needs to be implement first.

**Comment by efiop** [comment] 2019-03-25 09:28
It was probably about using spark with dvc.

**Comment by shcheklein** [comment] 2019-12-17 00:15
Scope is not clear. We don't support hdfs except for remotes now. Closing this for now.

**Closed by shcheklein** 2019-12-17 00:15 UTC
Labels: docs, enhancement, question

**Comment by jorgeorpinel** [comment] 2019-12-17 01:05
We have a good amount of mentions of HDFS in the context of external deps/outs as well as remote locations.

![image](https://user-images.githubusercontent.com/1477535/70955571-364bba00-2026-11ea-9fd3-f2d2aca7f703.png)

> It was probably about using spark with dvc.

Maybe this is more of a topic for a bog post?

**Comment by shcheklein** [comment] 2019-12-17 01:07
The problem is that we don't support it in a way we can write a blog post about ... at least not now.
