### ISSUE TITLE
document how to test remotes

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#311] opened 2019-05-10 07:52 UTC
These tests (mostly in `func/test_data_cloud.py`) are skipped by default and appear to be far from evident to set up. Not sure whether this should be added to contributing page or a new one.

**Comment by shcheklein** [comment] 2019-05-10 18:58
@Suor is it a duplicate of #238 ?

**Comment by shcheklein** [comment] 2019-05-12 20:26
closing a a duplicate of #238 . @Suor feel free to reopen it if I missed something.

**Closed by shcheklein** 2019-05-12 20:26 UTC
