### ISSUE TITLE
`exp run --reset` : Clarify behavior

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2745] opened 2021-08-23 12:56 UTC
> > If the user has a pipeline using checkpoints and runs `dvc exp run --reset` without changing the deps, the `checkpoints: true` stage(s) run(s) again.
>
> This is currently intended behavior, it's not really a bug. Doing `exp run --reset` is treated similarly to doing `dvc repro --force`, and will reproduce your entire pipeline from the initial checkpoint state.

I see. I guess that at least we should clarify this `--force` similarity in the docs, as it seems to be missing from https://dvc.org/doc/command-reference/exp/run#--reset

_From https://github.com/iterative/dvc/discussions/6475_

UPDATE: Also

> reset here is to reset the epochs to 0, so it is reasonable to restart the training

**Comment by dberenbaum** [comment] 2021-08-23 20:12
Agree that we should clarify, but let's decide on what the expected behavior is before changing the functionality or docs. I don't think the current docs are clear about whether the experiment will be run again.

Related: https://github.com/iterative/dvc/discussions/6475

**Comment by jorgeorpinel** [comment] 2021-08-25 16:12
If it's a small edit like just saying "this has the same result as `--reset` above" in the `--force` bullet then let's go for it meanwhile?

**Comment by jorgeorpinel** [comment] 2022-01-27 22:42
https://github.com/iterative/dvc/discussions/6475 seems to confirm that this is indeed a feature, not a bug. But there's also https://github.com/iterative/dvc/discussions/6104 (ongoing)... Do we close this for now @daavoo, @dberenbaum ?

**Comment by jorgeorpinel** [comment] 2022-01-27 22:49
Actually, this seems to be addressed by https://github.com/iterative/dvc.org/pull/3182/files#diff-162526d7eb1876fbb25840504db2c51860ae3c1b7af5b5f6431b0828c827189f 🙂

**Closed** 2022-01-28 03:39 UTC
Labels: type: enhancement, A: content
